#!/usr/bin/env bash
# A script that prints Best School 10x and hi after the 9th using while and if

a=1

while [ $a -le 10 ]
do
	echo "Best School"
	if [ $a -eq 9 ]
	then
		echo "Hi"
	fi
	((a++))
done
